version: '2'

services:

  standalone:
    image: apachepulsar/pulsar:2.7.1
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone"

  dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - standalone
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://standalone:8080
