name: pr

on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - "docs/**"
      - "*.md"

jobs:
  scala-2_12:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: docker-compose
          version: 1.0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Launch pulsar docker
        run: docker-compose up -d

      - name: run tests
        run: sbt ++2.12 test

  scala-2_13:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: docker-compose
          version: 1.0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Launch pulsar docker
        run: docker-compose up -d

      - name: run tests
        run: sbt ++2.13 test

  scala-3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: docker-compose
          version: 1.0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Launch pulsar docker
        run: docker-compose up -d

      - name: run tests
        run: sbt ++3.6 test
